# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"DATA_PATH": "01_dataset.ipynb",
         "data_name": "01_dataset.ipynb",
         "download_dataset": "01_dataset.ipynb",
         "data_fn": "01_dataset.ipynb"}

modules = ["boie/dataset.py"]

doc_url = "https://10zinten.github.io/ie/boie/"

git_url = "https://github.com/10zinten/boie/tree/master/"

def custom_doc_links(name): return None
